// <auto-generated />
using System;
using CinemaSolutionApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CinemaSolutionApi.Data.Migrations
{
    [DbContext(typeof(CinemaSolutionContext))]
    [Migration("20250806141520_modifyHoursMovies")]
    partial class modifyHoursMovies
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CinemaSolutionApi.Entities.Director", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Directors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LastName = "Stone",
                            Name = "Luca"
                        },
                        new
                        {
                            Id = 2,
                            LastName = "Silver",
                            Name = "Mateus"
                        },
                        new
                        {
                            Id = 3,
                            LastName = "Rivera",
                            Name = "Pedro"
                        },
                        new
                        {
                            Id = 4,
                            LastName = "O'Connell",
                            Name = "Liam"
                        },
                        new
                        {
                            Id = 5,
                            LastName = "Parker",
                            Name = "Olivia"
                        },
                        new
                        {
                            Id = 6,
                            LastName = "Harris",
                            Name = "Noah"
                        },
                        new
                        {
                            Id = 7,
                            LastName = "Collins",
                            Name = "Emma"
                        },
                        new
                        {
                            Id = 8,
                            LastName = "Reed",
                            Name = "William"
                        },
                        new
                        {
                            Id = 9,
                            LastName = "Bennett",
                            Name = "Sophia"
                        },
                        new
                        {
                            Id = 10,
                            LastName = "Foster",
                            Name = "James"
                        },
                        new
                        {
                            Id = 11,
                            LastName = "Morgan",
                            Name = "Isabella"
                        },
                        new
                        {
                            Id = 12,
                            LastName = "Hayes",
                            Name = "Benjamin"
                        },
                        new
                        {
                            Id = 13,
                            LastName = "Sullivan",
                            Name = "Ava"
                        },
                        new
                        {
                            Id = 14,
                            LastName = "Brooks",
                            Name = "Ethan"
                        });
                });

            modelBuilder.Entity("CinemaSolutionApi.Entities.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DirectorId")
                        .HasColumnType("integer");

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsInternational")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DirectorId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DirectorId = 1,
                            Duration = 115,
                            Image = "https://i.ibb.co/9Hg54sMZ/Gemini-Generated-Image-wdz3jywdz3jywdz3.png",
                            IsInternational = false,
                            Title = "The Secret of the Mirror"
                        },
                        new
                        {
                            Id = 2,
                            DirectorId = 2,
                            Duration = 98,
                            Image = "https://i.ibb.co/0pf183VG/Gemini-Generated-Image-wdz3jywdz3jywdz3-1.png",
                            IsInternational = false,
                            Title = "The Forgotten Shadow"
                        },
                        new
                        {
                            Id = 3,
                            DirectorId = 3,
                            Duration = 102,
                            Image = "https://i.ibb.co/HDnnNd5t/Gemini-Generated-Image-wdz3jywdz3jywdz3-2.png",
                            IsInternational = true,
                            Title = "Journey to the Star Heart"
                        },
                        new
                        {
                            Id = 4,
                            DirectorId = 1,
                            Duration = 100,
                            Image = "https://i.ibb.co/8DJdFYwJ/unnamed-6.png",
                            IsInternational = false,
                            Title = "The Secret of the Mirror 2"
                        },
                        new
                        {
                            Id = 5,
                            DirectorId = 4,
                            Duration = 105,
                            Image = "https://i.ibb.co/MrkwZZz/Gemini-Generated-Image-wdz3jywdz3jywdz3-3.png",
                            IsInternational = false,
                            Title = "Chronicles of the Hidden City"
                        },
                        new
                        {
                            Id = 6,
                            DirectorId = 5,
                            Duration = 60,
                            Image = "https://i.ibb.co/nMZV6ZC6/Gemini-Generated-Image-wdz3jywdz3jywdz3-4.png",
                            IsInternational = true,
                            Title = "The Dragon's Last Breath"
                        },
                        new
                        {
                            Id = 7,
                            DirectorId = 6,
                            Duration = 90,
                            Image = "https://i.ibb.co/3YjvSLQX/unnamed.png",
                            IsInternational = true,
                            Title = "Nights of Mist"
                        },
                        new
                        {
                            Id = 8,
                            DirectorId = 7,
                            Duration = 130,
                            Image = "https://i.ibb.co/4n92fjpr/Gemini-Generated-Image-wdz3jywdz3jywdz3-5.png",
                            IsInternational = false,
                            Title = "The Enigma of the Hourglass"
                        },
                        new
                        {
                            Id = 9,
                            DirectorId = 8,
                            Duration = 85,
                            Image = "https://i.ibb.co/9HVvNRY8/unnamed-1.png",
                            IsInternational = true,
                            Title = "The Guardians of the Forest"
                        },
                        new
                        {
                            Id = 10,
                            DirectorId = 9,
                            Duration = 110,
                            Image = "https://i.ibb.co/My8bMQyf/unnamed-2.png",
                            IsInternational = false,
                            Title = "Song of Sirens"
                        },
                        new
                        {
                            Id = 11,
                            DirectorId = 10,
                            Duration = 155,
                            Image = "https://i.ibb.co/901bbwy/Gemini-Generated-Image-wdz3jywdz3jywdz3-7.png",
                            IsInternational = true,
                            Title = "The Legend of the Awakening"
                        },
                        new
                        {
                            Id = 12,
                            DirectorId = 11,
                            Duration = 100,
                            Image = "https://i.ibb.co/vvd09nkH/Gemini-Generated-Image-6c9kjd6c9kjd6c9k-1.png",
                            IsInternational = true,
                            Title = "Echoes in the Void"
                        },
                        new
                        {
                            Id = 13,
                            DirectorId = 12,
                            Duration = 125,
                            Image = "https://i.ibb.co/bgV5f4Hh/unnamed-3.png",
                            IsInternational = false,
                            Title = "The Art of Flying"
                        },
                        new
                        {
                            Id = 14,
                            DirectorId = 13,
                            Duration = 95,
                            Image = "https://i.ibb.co/YT1d7NB2/Gemini-Generated-Image-6c9kjd6c9kjd6c9k-2.png",
                            IsInternational = true,
                            Title = "Whispers of the Past"
                        },
                        new
                        {
                            Id = 15,
                            DirectorId = 14,
                            Duration = 108,
                            Image = "https://i.ibb.co/8nqJHMbm/unnamed-4.png",
                            IsInternational = true,
                            Title = "The Dance of the Fireflies"
                        });
                });

            modelBuilder.Entity("CinemaSolutionApi.Entities.Screening", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FinishScreening")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("MovieId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("StartScreening")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.ToTable("Screenings");
                });

            modelBuilder.Entity("CinemaSolutionApi.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CinemaSolutionApi.Entities.Movie", b =>
                {
                    b.HasOne("CinemaSolutionApi.Entities.Director", "Director")
                        .WithMany("Movies")
                        .HasForeignKey("DirectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Director");
                });

            modelBuilder.Entity("CinemaSolutionApi.Entities.Screening", b =>
                {
                    b.HasOne("CinemaSolutionApi.Entities.Movie", "Movie")
                        .WithMany("Screenings")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("CinemaSolutionApi.Entities.Director", b =>
                {
                    b.Navigation("Movies");
                });

            modelBuilder.Entity("CinemaSolutionApi.Entities.Movie", b =>
                {
                    b.Navigation("Screenings");
                });
#pragma warning restore 612, 618
        }
    }
}
